apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cnrm-controller-manager
spec:
  privileged: false # Prevents creation of privileged Pods
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - "*"
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cnrm-webhook-manager
spec:
  privileged: false # Prevents creation of privileged Pods
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - "*"
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cnrm-resource-stats-recorder
spec:
  privileged: false # Prevents creation of privileged Pods
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - "*"
