apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install-bundle/crds.yaml
  - install-bundle/0-cnrm-system.yaml
  - cnrm-psp.yaml

patches:
  - patch-cnrm-system-namespace.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: cnrm-manager-cluster-role
    path: jsonpatch-cnrm-clusterrole.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: cnrm-recorder-role
    path: jsonpatch-cnrm-recorder-role.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: cnrm-webhook-role
    path: jsonpatch-cnrm-webhook-role.yaml
