apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-system
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-system
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: istio-system
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-cni
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: istio-system
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: istio-cni
