# ClusterRole to use podsecuritypolicy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadgenerator
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - loadgenerator
---
# Authorize all service accounts in namespace to use the podsecuritypolicy
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadgenerator
  namespace: loadgenerator
roleRef:
  kind: ClusterRole
  name: loadgenerator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgenerator
  namespace: loadgenerator
  annotations:
    iam.gke.io/gcp-service-account: microservices@OPS_PROJECT_ID.iam.gserviceaccount.com
