apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: autoneg
  namespace: autoneg-system
spec:
  privileged: false # Prevents creation of privileged Pods
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - "*"
