apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoneg-system
  namespace: autoneg-system
  annotations:
    iam.gke.io/gcp-service-account: autoneg-system@${PROJECT_ID}.iam.gserviceaccount.com