apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autoneg-system

resources:
  - autoneg-system-namespace.yaml
  - autoneg-serviceaccount.yaml
  - autoneg-psp.yaml
  - autoneg.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: autoneg-manager-role
    path: jsonpatch-autoneg-cluster-role-psp.yaml
