apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: microservices
  namespace: cnrm-system
spec:
  displayName: Microservices
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: microservices-project-logswriter
  namespace: cnrm-system
spec:
  member: serviceAccount:microservices@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/logging.logWriter
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: microservices-project-metricwriter
  namespace: cnrm-system
spec:
  member: serviceAccount:microservices@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/monitoring.metricWriter
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: microservices-project-monitoringviewer
  namespace: cnrm-system
spec:
  member: serviceAccount:microservices@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/monitoring.viewer
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: microservices-project-clouddebugger
  namespace: cnrm-system
spec:
  member: serviceAccount:microservices@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/clouddebugger.agent
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: microservices-project-cloudprofiler
  namespace: cnrm-system
spec:
  member: serviceAccount:microservices@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/cloudprofiler.agent
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: microservices-project-cloudtrace
  namespace: cnrm-system
spec:
  member: serviceAccount:microservices@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/cloudtrace.agent
  resourceRef:
    kind: Project
